import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header"
import Footer from "@/components/layout/Footer"
import { AppProvider } from "@/components/AppContext";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });

export const metadata = {
  title: "Cheat Day Bakes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex flex-col min-h-screen">
          <AppProvider>
            <Toaster />
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </AppProvider>
        </div>
      </body>
    </html>
  );
}
